
version: "3"
services:
    db:
        build: ./db/
        ports:
            - "5432:5432"
        volumes:
            - ./db/initdb:/docker-entrypoint-initdb.d
            - ./db:/birthday_service
    backend:
        build: ./backend/
        environment:
            PGHOST: db
            PGPORT: 5432
            PGUSER: postgres
        ports:
            - "3000:3000"
        links:
            - db
        volumes:
            - ./backend:/birthday_service

