
all:

    hosts:
        nodeA:
            ansible_host: 192.168.111.11
            ansible_user: vagrant
            ansible_ssh_private_key_file: ssh/id_rsa
        nodeB:
            ansible_host: 192.168.111.12
            ansible_user: vagrant
            ansible_ssh_private_key_file: ssh/id_rsa
        node-backend:
            ansible_host: 192.168.111.18
            ansible_user: vagrant
            ansible_ssh_private_key_file: ssh/id_rsa
    vars:
        consul_servers:  '["nodeA", "nodeB"]'

    children:
        db_nodes:
            vars:
                primary_node: nodeA
            hosts:
                nodeA:
                    repmgr_node_idx: 1
                nodeB:
                    repmgr_node_idx: 2
        consul_nodes:
            vars:
                consul_role: server
            hosts:
                nodeA:
                    consul_bootstrap: "true"
                nodeB:
                    consul_bootstrap: "false"
        backend_nodes:
            vars:
                consul_role: agent
            hosts:
                node-backend:
