
- name: Ensure repmgr user in postgres
  postgresql_user:
      name: repmgr
      role_attr_flags: SUPERUSER,REPLICATION
      password: secret_password
  become_user: postgres

- name: Ensure repmgr database in postgres
  postgresql_db:
      name: repmgr
      owner: repmgr
  become_user: postgres

- name: register primary
  command:  repmgr -f /etc/repmgr.conf primary register
  become_user: postgres
  when: not postgres_initialised

- name: ensure file /etc/postgres_initialised
  file:
      path: /etc/postgres_initialised
      state: touch
  when: not postgres_initialised
